"use client";

import { useState, useTransition } from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { Controller, useForm, useWatch } from "react-hook-form";
import { Pencil, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import type { Technology } from "@/db/schema";
import { deleteTechnology, saveTechnology } from "@/app/admin/actions";
import { technologySchema, type TechnologyInput } from "@/lib/validation";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Field, FieldError, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { UploadField } from "@/components/admin/upload-field";
import { cleanupUpload } from "@/lib/cleanup-upload";

const empty: TechnologyInput = { name: "", category: "", displayOrder: 0, visible: true };

export function TechnologiesManager({ items }: { items: Technology[] }) { const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Technology>(); const launch = (item?: Technology) => { setEditing(item); setOpen(true); }; return <><div className="mb-6 flex justify-end"><Button onClick={() => launch()} className="bg-accent-lime text-black hover:bg-white"><Plus className="size-4" />Add technology</Button></div><div className="overflow-hidden rounded-xl border border-white/10">{items.length ? items.map((item) => <article key={item.id} className="flex items-center justify-between gap-4 border-b border-white/10 p-4 last:border-b-0"><div><h2 className="font-semibold">{item.name}</h2><p className="mt-1 text-xs text-muted-foreground">{item.category} · {item.visible ? "Visible" : "Hidden"} · Order {item.displayOrder}</p></div><div className="flex gap-1"><Button size="icon-sm" variant="ghost" onClick={() => launch(item)} aria-label={`Edit ${item.name}`}><Pencil className="size-4" /></Button><DeleteTechnology item={item} /></div></article>) : <p className="py-16 text-center text-sm text-muted-foreground">No technologies yet.</p>}</div><TechnologyDialog key={editing?.id ?? "new"} open={open} onOpenChange={setOpen} item={editing} /></>; }

function TechnologyDialog({ open, onOpenChange, item }: { open: boolean; onOpenChange: (v: boolean) => void; item?: Technology }) { const form = useForm<TechnologyInput>({ resolver: zodResolver(technologySchema), defaultValues: item ? { name: item.name, category: item.category, websiteUrl: item.websiteUrl ?? undefined, iconKey: item.iconKey ?? undefined, iconAlt: item.iconAlt ?? undefined, displayOrder: item.displayOrder, visible: item.visible } : empty }); const { register, control, setValue, setError, handleSubmit, formState: { errors, isSubmitting } } = form; const iconKey = useWatch({ control, name: "iconKey" }); async function submit(values: TechnologyInput) { const result = await saveTechnology(values, item?.id); if (!result.ok) { if (values.iconKey && values.iconKey !== item?.iconKey) { await cleanupUpload(values.iconKey); setValue("iconKey", undefined); } Object.entries(result.fields ?? {}).forEach(([name, messages]) => setError(name as keyof TechnologyInput, { message: messages[0] })); toast.error(result.message); return; } toast.success(item ? "Technology updated." : "Technology created."); onOpenChange(false); window.location.reload(); } return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{item ? "Edit technology" : "Add technology"}</DialogTitle><DialogDescription>Technologies are grouped by category on the public site.</DialogDescription></DialogHeader><form onSubmit={handleSubmit(submit)}><FieldGroup className="gap-5"><TField label="Name" error={errors.name?.message} props={register("name")} /><TField label="Category" error={errors.category?.message} props={register("category")} /><TField label="Website URL" type="url" error={errors.websiteUrl?.message} props={register("websiteUrl")} /><TField label="Display order" type="number" error={errors.displayOrder?.message} props={register("displayOrder", { valueAsNumber: true })} /><div className="grid gap-5 sm:grid-cols-2"><UploadField resourceType="icon" value={iconKey} onChange={(key) => setValue("iconKey", key)} /><TField label="Icon alt text" error={errors.iconAlt?.message} props={register("iconAlt")} /></div><Controller control={control} name="visible" render={({ field }) => <Field orientation="horizontal" className="rounded-xl border border-white/10 p-4"><FieldLabel className="flex-1" htmlFor="technology-visible">Visible</FieldLabel><Switch id="technology-visible" checked={field.value} onCheckedChange={field.onChange} /></Field>} /></FieldGroup><DialogFooter className="mt-6"><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={isSubmitting} className="bg-accent-lime text-black hover:bg-white">Save technology</Button></DialogFooter></form></DialogContent></Dialog>; }
function TField({ label, type = "text", error, props }: { label: string; type?: string; error?: string; props: React.InputHTMLAttributes<HTMLInputElement> }) { return <Field data-invalid={Boolean(error)}><FieldLabel htmlFor={props.name}>{label}</FieldLabel><Input id={props.name} type={type} {...props} /><FieldError>{error}</FieldError></Field>; }
function DeleteTechnology({ item }: { item: Technology }) { const [pending, start] = useTransition(); return <AlertDialog><AlertDialogTrigger asChild><Button size="icon-sm" variant="ghost" aria-label={`Delete ${item.name}`}><Trash2 className="size-4" /></Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete “{item.name}”?</AlertDialogTitle><AlertDialogDescription>This permanently removes the technology and its managed icon.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction disabled={pending} className="bg-destructive text-white" onClick={() => start(async () => { const result = await deleteTechnology(item.id); if (result.ok) { toast.success("Technology deleted."); window.location.reload(); } else { toast.error(result.message); } })}>Delete</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>; }
